# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Layer 8 Links"

# Avatar image path
avatar: "./images/avatar.png"

# Name section text
name: "@layer8"

# Tagline section text
tagline: >-
    We are the cybersecurity club of Cal State Northridge, Layer 8. We focus on educating our members via hands on learning. We meet every Monday in JD1600A from 7 PM to 8:30 PM, and every Saturday in JD1602 from 12 PM to 5 PM. 

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-discord"
      text: "Discord"
      url: "https://discord.gg/fu2zvq6"
      alt: "Most of our activity and communication happens in our Discord server"
      title: "Discord Link" 
      target: "_blank"
  - link:
      icon: "fa-classic fa-m"
      text: "Matasync"
      url: "https://csun.campuslabs.com/engage/organization/layer-8"
      alt: "Matasync is CSUN's official platform for communicating with clubs."
      title: "Matasync"
      target: "_blank"
  - link:
      icon: "fa-classic fa-globe"
      text: "Website"
      url: "https://csunlayer8.com"
      alt: "Matasync is CSUN's official platform for communicating with clubs."
      title: "Is this even used?"
      target: "_blank"



# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/csun_layer8/"
      title: "Instagram"
      alt: "Instagram (alt)"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/csunlayer8"
      title: "Github"
      alt: "GitHub (alt)"
      target: "_blank"
  - social:
      icon: "fa-classic fa-globe"
      url: "https://csunlayer8.com"
      alt: "Website"
      target: "_blank"

# Footer text
footer: >
    Hi there! Join our Discord to keep up with our events and chat with our members.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://csunlayer8.com" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
